//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChanhDuongApiConsumer.ChanhDuongAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://chanhduong.org/", ConfigurationName="ChanhDuongAPI.ChuaNgotServiceSoap")]
    public interface ChuaNgotServiceSoap {
        
        // CODEGEN: Generating message contract since element name FibonacciResult from namespace http://chanhduong.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://chanhduong.org/Fibonacci", ReplyAction="*")]
        ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciResponse Fibonacci(ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://chanhduong.org/Fibonacci", ReplyAction="*")]
        System.Threading.Tasks.Task<ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciResponse> FibonacciAsync(ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://chanhduong.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://chanhduong.org/XmlToJson", ReplyAction="*")]
        ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonResponse XmlToJson(ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://chanhduong.org/XmlToJson", ReplyAction="*")]
        System.Threading.Tasks.Task<ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonResponse> XmlToJsonAsync(ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FibonacciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fibonacci", Namespace="http://chanhduong.org/", Order=0)]
        public ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciRequestBody Body;
        
        public FibonacciRequest() {
        }
        
        public FibonacciRequest(ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://chanhduong.org/")]
    public partial class FibonacciRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int n;
        
        public FibonacciRequestBody() {
        }
        
        public FibonacciRequestBody(int n) {
            this.n = n;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FibonacciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FibonacciResponse", Namespace="http://chanhduong.org/", Order=0)]
        public ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciResponseBody Body;
        
        public FibonacciResponse() {
        }
        
        public FibonacciResponse(ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://chanhduong.org/")]
    public partial class FibonacciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FibonacciResult;
        
        public FibonacciResponseBody() {
        }
        
        public FibonacciResponseBody(string FibonacciResult) {
            this.FibonacciResult = FibonacciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJson", Namespace="http://chanhduong.org/", Order=0)]
        public ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonRequestBody Body;
        
        public XmlToJsonRequest() {
        }
        
        public XmlToJsonRequest(ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://chanhduong.org/")]
    public partial class XmlToJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public XmlToJsonRequestBody() {
        }
        
        public XmlToJsonRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonResponse", Namespace="http://chanhduong.org/", Order=0)]
        public ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonResponseBody Body;
        
        public XmlToJsonResponse() {
        }
        
        public XmlToJsonResponse(ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://chanhduong.org/")]
    public partial class XmlToJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlToJsonResult;
        
        public XmlToJsonResponseBody() {
        }
        
        public XmlToJsonResponseBody(string XmlToJsonResult) {
            this.XmlToJsonResult = XmlToJsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChuaNgotServiceSoapChannel : ChanhDuongApiConsumer.ChanhDuongAPI.ChuaNgotServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChuaNgotServiceSoapClient : System.ServiceModel.ClientBase<ChanhDuongApiConsumer.ChanhDuongAPI.ChuaNgotServiceSoap>, ChanhDuongApiConsumer.ChanhDuongAPI.ChuaNgotServiceSoap {
        
        public ChuaNgotServiceSoapClient() {
        }
        
        public ChuaNgotServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChuaNgotServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChuaNgotServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChuaNgotServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciResponse ChanhDuongApiConsumer.ChanhDuongAPI.ChuaNgotServiceSoap.Fibonacci(ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciRequest request) {
            return base.Channel.Fibonacci(request);
        }
        
        public string Fibonacci(int n) {
            ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciRequest inValue = new ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciRequest();
            inValue.Body = new ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciRequestBody();
            inValue.Body.n = n;
            ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciResponse retVal = ((ChanhDuongApiConsumer.ChanhDuongAPI.ChuaNgotServiceSoap)(this)).Fibonacci(inValue);
            return retVal.Body.FibonacciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciResponse> ChanhDuongApiConsumer.ChanhDuongAPI.ChuaNgotServiceSoap.FibonacciAsync(ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciRequest request) {
            return base.Channel.FibonacciAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciResponse> FibonacciAsync(int n) {
            ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciRequest inValue = new ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciRequest();
            inValue.Body = new ChanhDuongApiConsumer.ChanhDuongAPI.FibonacciRequestBody();
            inValue.Body.n = n;
            return ((ChanhDuongApiConsumer.ChanhDuongAPI.ChuaNgotServiceSoap)(this)).FibonacciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonResponse ChanhDuongApiConsumer.ChanhDuongAPI.ChuaNgotServiceSoap.XmlToJson(ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonRequest request) {
            return base.Channel.XmlToJson(request);
        }
        
        public string XmlToJson(string xml) {
            ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonRequest inValue = new ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonRequest();
            inValue.Body = new ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonResponse retVal = ((ChanhDuongApiConsumer.ChanhDuongAPI.ChuaNgotServiceSoap)(this)).XmlToJson(inValue);
            return retVal.Body.XmlToJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonResponse> ChanhDuongApiConsumer.ChanhDuongAPI.ChuaNgotServiceSoap.XmlToJsonAsync(ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonRequest request) {
            return base.Channel.XmlToJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonResponse> XmlToJsonAsync(string xml) {
            ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonRequest inValue = new ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonRequest();
            inValue.Body = new ChanhDuongApiConsumer.ChanhDuongAPI.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            return ((ChanhDuongApiConsumer.ChanhDuongAPI.ChuaNgotServiceSoap)(this)).XmlToJsonAsync(inValue);
        }
    }
}
